# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "602c66dde2d7b95f2558da295d857c81"
application_url = "https://reflections-rarely-courses-short.trycloudflare.com"
embedded = true
name = "marketing"
handle = "marketing-90"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://reflections-rarely-courses-short.trycloudflare.com/auth/callback",
  "https://reflections-rarely-courses-short.trycloudflare.com/auth/shopify/callback",
  "https://reflections-rarely-courses-short.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "iquotify.myshopify.com"
automatically_update_urls_on_dev = true
